### ISSUE TITLE
Why the number of the input channels is 4?

### ISSUE THREAD

**Issue by bearpaw** [shihenw/convolutional-pose-machines-release#1]
Hi, @shihenw ,

I notice that the number of input channels is 4, and the 4-th channel is a Gaussian-like scoremap whose values are in range [0, 1]. 

So what is this channel used for? Thank you.

**Comment by shihenw** [comment]
As you observed, the 4th channel is a gaussian peak centered at rough position of the interested person. This helps the network to disambiguate the body parts of adjacent people. The 4-th channel is inputted to the subsequent stages (T = 2,3,...) of convolutional pose machines, as described in the paper.

In MPII and FLIC dataset the center is provided for each testing sample (in different ways), and in LSP we simply use the center of the image since the LSP images are usually tightly cropped. For general images in `test/CPM_demo.m`, the center position is inferred from the bounding box that user gives.

**Comment by priyapaul** [comment]
@bearpaw  Couls you please tell, where is the code related to center map can be found?
