### ISSUE TITLE
Why use the same two: "label_lower" and "label_1st_lower"?

### ISSUE THREAD

**Issue by WolffyChen** [shihenw/convolutional-pose-machines-release#52]
Hello Wei,

I have found that the heatmap label "label_lower" split to the same two: "label_lower" and "label_1st_lower" int the train prototxt. And the loss of stage1 use "label_1st_lower", while stage2~6 use "label_lower". Since "label_lower" and "label_1st_lower" are exactly same, why not only use one?

Thank you very much!
Hope Reply.

**Comment by ds2268** [comment]
Look at #30

**Comment by WolffyChen** [comment]
Thank you very much! I get it! @ds2268

**Comment by BrettLL** [comment]
@ds2268 @WolffyChen  I see #30 but still don't understand why it trained use uninterested person limbs points? We only train interested person and isn't that right?

**Comment by ds2268** [comment]
As per my understanding, you can look at the first stage as a limb "detector", so you need as much data as possible to train the first stage to detect separate parts also connected to the small receptive field in the first stage as discussed in #30. Because the receptive field is small in the first stage the network can't see the difference among people and it would confuse it as there would be limbs present  but not annotated which would contradict the learning. In later stages you provide also "center_map" to help the network focus on the person that you are interested in and further regress the body part locations to the correct locations and to find and learn correct correspondences and parts relationships.

@shihenw can provide further details if needed

**Comment by BrettLL** [comment]
@ds2268 Is that said, the first-stage wants to learn where all the person limbs and the other stages learn the interested person limbs? If we feed a multi-person image to the net, the first stage would give all the persons' limbs points?
