### ISSUE TITLE
Hi, questions about the paper.

### ISSUE THREAD

**Issue by tangyudi** [shihenw/convolutional-pose-machines-release#7]
I have some thing do not understand in your paper.Thanks for your reply.
(1)What is the meaning of receptive fields? Is it means after the first convolution and pool the output is smaller than the original image,so use the same convolution on the output of conv1-poo1 can receive larger receptive fields?Does larger kernel_size of convolution means larger receptive fields?
(2)What is the meaning of  '8× downscaled heatmaps' and how to do this?
(3)'the receptive field of the second stage output on the belief maps of the first stage is set to 31 × 31'
how is the 31 × 31 been calculated?
(4)Your label contain 14 points without background ,why the network can give a score of a background patch?
Thank you!

**Comment by shihenw** [comment]
(1) Check [this page](http://stats.stackexchange.com/questions/142606/receptive-field-of-neurons-in-lenet)
(2) Because we used 3 times of 2x pool, so in total the image is down-sampled by 8x.
(3) 31 comes from the three 11x11 convolution layers applied on the previous belief maps: 1 + (11-1) + (11-1) + (11-1).
(4) Our label actually contains two sets of P+1 ideal maps, as described in the paper, where the plus one is for background.

**Comment by XiaoSun89** [comment]
Hi, thanks for sharing the work! I have an extra question:

What is the exact meaning of "center_map"(generate in "Slice" layer, and used in all "Concat")? Is it just a copy of the original image patch? If so, what is the difference between the "image" and "center_map" blob? I can't find any clue in the pipeline figure 2 in the paper, maybe I'v missed some details.

Thanks for your reply!

**Comment by shihenw** [comment]
See #1.
